### ISSUE TITLE
Add support for Recomposer .rcp/.r36/.g18/.g36 format

### ISSUE THREAD

**Issue by internetakias** [stuerp/foo_midi#37] opened 2024-04-16 22:59 UTC
So back in the 90s in Japan one very popular program used for midi composition was [Recomposer](https://ja.m.wikipedia.org/wiki/%E3%83%AC%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%82%B6), and it was used by a number of people including, of course ZUN, the creator of Touhou Project: https://archive.org/details/ZUN_MIDI_1
However, support for its playback now is scarce, especially in western made programs, so it'd be great if this plugin added support for the format for easier accessibility.
TiMidity has support for the format so I'd assume you could [study its source code](https://github.com/Distrotech/TiMidity/blob/master/timidity/rcp.c) to figure out how to implement it in this component.

**Comment by stuerp** [comment] 2024-04-17 05:25
Thx. for the suggestion. I'll have a look at it.

**Comment by basic2004** [comment] 2024-05-03 06:30
That's good news when implemented!
Some files of these format contains .gsd/.cm6, They're like system exclusive.

**Comment by stuerp** [comment] 2024-05-06 16:42
@basic2004 ,
I've started implementing this but it's going to take a while. Do you know where I can find example files of the 4 types? I only found a couple .rcp files.

**Comment by stuerp** [comment] 2024-05-07 20:12
> So back in the 90s in Japan one very popular program used for midi composition was [Recomposer](https://ja.m.wikipedia.org/wiki/%E3%83%AC%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%82%B6), and it was used by a number of people including, of course ZUN, the creator of Touhou Project: https://archive.org/details/ZUN_MIDI_1 However, support for its playback now is scarce, especially in western made programs, so it'd be great if this plugin added support for the format for easier accessibility. TiMidity has support for the format so I'd assume you could [study its source code](https://github.com/Distrotech/TiMidity/blob/master/timidity/rcp.c) to figure out how to implement it in this component.

Same question: do you have any more examples besides the ZUN files? It only has a couple .rcp files.

**Comment by Mohamed00** [comment] 2024-05-09 15:22
Here are 30 examples of RCP files, as well as some G36. Let me know if you need more, I have lots of files in this format.
[RCP.zip](https://github.com/stuerp/foo_midi/files/15264168/RCP.zip)

**Comment by stuerp** [comment] 2024-05-09 19:56
@Mohamed00, Thx.

**Comment by stuerp** [comment] 2024-05-11 20:25
@internetakias, @basic2004 , @Mohamed00,

have a look at https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha1

**Comment by Mohamed00** [comment] 2024-05-11 21:16
Support seems to be pretty good so far, with sysex-heavy files playing pretty well. One thing I noticed is that some Japanese text isn't
[RCP broken text.zip](https://github.com/stuerp/foo_midi/files/15284324/RCP.broken.text.zip)
 being converted properly. Here are some example RCPs with the problem.

**Comment by internetakias** [comment] 2024-05-11 21:38
I'm experiencing a lot of crashes for some reason on latest stable 64 bit foobar, also this 32 channel midi seems to be playing out of order for some reason? I've attached the .g36 original file, a midi conversion and two renders, one of how the plugin plays the .g36, and another one that shows how it's supposed to sound. Using Secret Sauce as it's for the SC-88Pro.
[NIGHT.zip](https://github.com/stuerp/foo_midi/files/15284373/NIGHT.zip)

**Comment by stuerp** [comment] 2024-05-11 23:25
@internetakias , alpha2 should fix this. A big chunk of code was not executed in Release builds...

**Comment by Mohamed00** [comment] 2024-05-12 13:25
Found another issue. I noticed that when a file path contains non-ASCII characters and an RCP has a corresponding GSD, foo_midi is unable to locate the GSD. Here's an example. [あのまりあ.zip](https://github.com/stuerp/foo_midi/files/15286388/default.zip)

**Comment by basic2004** [comment] 2024-05-12 14:20
I tested alpha2, played 3DAYS.RCP with GSD, works well.

**Comment by Mohamed00** [comment] 2024-05-12 14:29
Did you put it in a path with non-ASCII characters? Whenever I do, I get this. Unable to open item for playback (Sequence file conversion failed: GSD control file "C:\あのまりあ\3DAYS.GSD" not found.):
"C:\あのまりあ\3DAYS.RCP"

**Comment by basic2004** [comment] 2024-05-12 14:49
And here is another Anomaria(あのまりあ)'s RCP files, these works well with alpha2.
[anomaria.zip](https://github.com/stuerp/foo_midi/files/15286659/anomaria.zip)
played BAMBOO.RCP with GSD works well too.

**Comment by stuerp** [comment] 2024-05-12 14:52
> Found another bug. I noticed that when a file path contains non-ASCII characters and an RCP has a corresponding GSD, foo_midi is unable to locate the GSD. Here's an example. [あのまりあ.zip](https://github.com/stuerp/foo_midi/files/15286388/default.zip)

I'm current cleaning up and hardening the code. I start from the Valley Bell code (which I still use to binary compare the generated MIDI files with) but it's ASCII-only. fb2k uses UTF-8 internally so I'm adapting the code.

**Comment by basic2004** [comment] 2024-05-12 15:01
I found another bug, when playing TROPIC88.RCP, I heard some strange guitar sound.
https://soundcloud.com/gs_standard/something-tropical-by-anomaria-roland-sc88-1996?in=gs_standard%2Fsets%2Fanomaria-midi
This link is recoreded from real hardware, maybe.

**Comment by Mohamed00** [comment] 2024-05-12 15:11
Perhaps caused by the use of the ＲＣＣ compression? The notes for both TROPIC88 and LOST88P mention the use of this, and both have issues when played with foo_midi. In LOST88P, for example, the timing of the guitars at 3:43 is off compared to a MIDI conversion made with rcpconv.exe.

**Comment by stuerp** [comment] 2024-05-12 18:27
> Perhaps caused by the use of the ＲＣＣ compression? The notes for both TROPIC88 and LOST88P mention the use of this, and both have issues when played with foo_midi. In LOST88P, for example, the timing of the guitars at 3:43 is off compared to a MIDI conversion made with rcpconv.exe.

Frankly, I don't know what I'm supposed to hear. The current foo_midi rendition with Secret Sauce sound fine to me. Can you share the MIDI conversion so I can do a comparison of the events?

**Comment by Mohamed00** [comment] 2024-05-12 18:57
Sure, here's a conversion.

**Comment by Mohamed00** [comment] 2024-05-12 18:57
[LOST88P.zip](https://github.com/stuerp/foo_midi/files/15287367/LOST88P.zip)
Oops, forgot to add the file.

**Comment by stuerp** [comment] 2024-05-12 19:03
Alpha 3 adds support for Unicode paths.
https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha3

**Comment by Mohamed00** [comment] 2024-05-13 23:10
Yep, 3Days.RCP is working in Unicode paths now, thanks. Also in case you need it as a reference, here's the RCP converter I used to convert LOST88P to MIDI. It seems to lack support for things like RCP loops, but otherwise generally converts well.
[RCPCVC.zip](https://github.com/stuerp/foo_midi/files/15300811/RCPCVC.zip)

**Comment by internetakias** [comment] 2024-05-13 23:29
> @internetakias , alpha2 should fix this. A big chunk of code was not executed in Release builds...
> 
> Edit: I was too fast: alpha2 fixes the conversion bug but I hear the difference between the converted sequence and your OPUS file. There's a drum roll at the start. I'll try to find the cause.
> 
> Edit2: The Yu-No files seem to cause problems. I don't have them to replicate the problem.
> 
> Edit3: The missing drum roll is rendered correctly by Secret Sauce. So the conversion seems correct but I don't know why the other players swallow the events.


No unfortunately the problem isn't with the drum loop at the beginning, it's with the guitar parts that use channels B1-16/Port 2, you'll notice that they play really out of order in the .g36 compared to the midi conversion if you listen to the full thing.
Also, I'm still experiencing crashes even after reinstalling foobar and deleting all of my user data and other components.
[crash reports.zip](https://github.com/stuerp/foo_midi/files/15300876/crash.reports.zip)

**Comment by stuerp** [comment] 2024-05-14 04:34
> > @internetakias , alpha2 should fix this. A big chunk of code was not executed in Release builds...
> > Edit: I was too fast: alpha2 fixes the conversion bug but I hear the difference between the converted sequence and your OPUS file. There's a drum roll at the start. I'll try to find the cause.
> > Edit2: The Yu-No files seem to cause problems. I don't have them to replicate the problem.
> > Edit3: The missing drum roll is rendered correctly by Secret Sauce. So the conversion seems correct but I don't know why the other players swallow the events.
> 
> No unfortunately the problem isn't with the drum loop at the beginning, it's with the guitar parts that use channels B1-16/Port 2, you'll notice that they play really out of order in the .g36 compared to the midi conversion if you listen to the full thing. Also, I'm still experiencing crashes even after installing alpha3 and reinstalling foobar and deleting all of my user data and other components. [crash reports.zip](https://github.com/stuerp/foo_midi/files/15300876/crash.reports.zip)

Like I said in Edit2: the crash occurs while processing Yu-No files. Without those files I can't determine what the problem is:

[159750ms] Media library indexing: file://D:\<edit>\YU-NO\PYN_051.RCP

**Comment by internetakias** [comment] 2024-05-14 12:20
> > > @internetakias , alpha2 should fix this. A big chunk of code was not executed in Release builds...
> > > Edit: I was too fast: alpha2 fixes the conversion bug but I hear the difference between the converted sequence and your OPUS file. There's a drum roll at the start. I'll try to find the cause.
> > > Edit2: The Yu-No files seem to cause problems. I don't have them to replicate the problem.
> > > Edit3: The missing drum roll is rendered correctly by Secret Sauce. So the conversion seems correct but I don't know why the other players swallow the events.
> > 
> > 
> > No unfortunately the problem isn't with the drum loop at the beginning, it's with the guitar parts that use channels B1-16/Port 2, you'll notice that they play really out of order in the .g36 compared to the midi conversion if you listen to the full thing. Also, I'm still experiencing crashes even after installing alpha3 and reinstalling foobar and deleting all of my user data and other components. [crash reports.zip](https://github.com/stuerp/foo_midi/files/15300876/crash.reports.zip)
> 
> Like I said in Edit2: the crash occurs while processing Yu-No files. Without those files I can't determine what the problem is:
> 
> [159750ms] Media library indexing: file://D:<edit>\YU-NO\PYN_051.RCP

You're right, it totally slipped my mind. Here you go: 
[YU-NO.zip](https://github.com/stuerp/foo_midi/files/15308213/YU-NO.zip)

**Comment by stuerp** [comment] 2024-05-14 17:12
F

> > > > @internetakias , alpha2 should fix this. A big chunk of code was not executed in Release builds...
> > > > Edit: I was too fast: alpha2 fixes the conversion bug but I hear the difference between the converted sequence and your OPUS file. There's a drum roll at the start. I'll try to find the cause.
> > > > Edit2: The Yu-No files seem to cause problems. I don't have them to replicate the problem.
> > > > Edit3: The missing drum roll is rendered correctly by Secret Sauce. So the conversion seems correct but I don't know why the other players swallow the events.
> > > 
> > > 
> > > No unfortunately the problem isn't with the drum loop at the beginning, it's with the guitar parts that use channels B1-16/Port 2, you'll notice that they play really out of order in the .g36 compared to the midi conversion if you listen to the full thing. Also, I'm still experiencing crashes even after installing alpha3 and reinstalling foobar and deleting all of my user data and other components. [crash reports.zip](https://github.com/stuerp/foo_midi/files/15300876/crash.reports.zip)
> > 
> > 
> > Like I said in Edit2: the crash occurs while processing Yu-No files. Without those files I can't determine what the problem is:
> > [159750ms] Media library indexing: file://D:\YU-NO\PYN_051.RCP
> 
> You're right, it totally slipped my mind. Here you go: [YU-NO.zip](https://github.com/stuerp/foo_midi/files/15308213/YU-NO.zip)

Thx. and fixed in [alpha4](https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha4).

A division by 0 error due to an unexpected tempo change value. I still have to investigate why that exception escaped the exception handler... It should not have caused a crash.

**Comment by stuerp** [comment] 2024-05-16 15:15
> I tried [alpha5](https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha5), these links are images of mismatched mixed-encoding detection, from [anomaria.zip](https://github.com/stuerp/foo_midi/files/15286659/anomaria.zip)
> 
> ![3days.rcp](https://private-user-images.githubusercontent.com/24873576/331208102-11c4dede-ba05-42d7-82fd-8814310cd8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMDItMTFjNGRlZGUtYmEwNS00MmQ3LTgyZmQtODgxNDMxMGNkOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNzU5M2I0MDIzYTM5NDA3YmFkYjgwY2Y3ZTAzOGFkMzVkNjJkYmZhZjc5OGI4YzNlMDMxYTZlNDNiMjlhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYEWAACvg2zlKzlClYAKyNoLO2_wiZ3je1TC1gvnaUw) ![g_s201.rcp](https://private-user-images.githubusercontent.com/24873576/331208108-b9d64ebb-815e-43ac-afc3-0184400ed71a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMDgtYjlkNjRlYmItODE1ZS00M2FjLWFmYzMtMDE4NDQwMGVkNzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTMxNWIyNDhmNjcwZDhjYjI5MTU4MjhjMzJlM2NjYzcxNTEwYjBiZWQwMmMxN2IyYTI5M2M2MGI1ZDg1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y6sjQ5zQUKcsPR9u6lEQMBlEkx-BGSk_YEzNvcpJ0ik) ![mega.rcp](https://private-user-images.githubusercontent.com/24873576/331208112-86407630-de72-4cb5-ae4c-7beda944c986.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMTItODY0MDc2MzAtZGU3Mi00Y2I1LWFlNGMtN2JlZGE5NDRjOTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTdmYTBjMmY0ZWUwZjcxY2VkZGY5ZTliODAzMmI2YmY4YmEzMGFjYmY2MzQ4NGQxZmVmZjZiMGU5N2FjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nin8pfQxq2O0GxdsR3Rb29pjiQiPF9uXyis0nyN4_0Q) ![mnmchn88.rcp](https://private-user-images.githubusercontent.com/24873576/331208117-571c0e8d-3d71-4f0b-90c4-9b1a689e79db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMTctNTcxYzBlOGQtM2Q3MS00ZjBiLTkwYzQtOWIxYTY4OWU3OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZDJkNGUwZjRmZmViZmVjMzYyYmFmY2JlNDQwNmVjMzRkZDc5NjNmMmI3ODJkYmI3ODE1YmUyNTg2NGYwY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TphCOL7f4KAKP4Q9WO5tkpMFDoF2GfbPWiezBccG1kM)



> I tried [alpha5](https://github.com/stuerp/foo_midi/releases/tag/v2.11.0.0-alpha5), these links are images of mismatched mixed-encoding detection, from [anomaria.zip](https://github.com/stuerp/foo_midi/files/15286659/anomaria.zip)
> 
> ![3days.rcp](https://private-user-images.githubusercontent.com/24873576/331208102-11c4dede-ba05-42d7-82fd-8814310cd8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMDItMTFjNGRlZGUtYmEwNS00MmQ3LTgyZmQtODgxNDMxMGNkOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNzU5M2I0MDIzYTM5NDA3YmFkYjgwY2Y3ZTAzOGFkMzVkNjJkYmZhZjc5OGI4YzNlMDMxYTZlNDNiMjlhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYEWAACvg2zlKzlClYAKyNoLO2_wiZ3je1TC1gvnaUw) ![g_s201.rcp](https://private-user-images.githubusercontent.com/24873576/331208108-b9d64ebb-815e-43ac-afc3-0184400ed71a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMDgtYjlkNjRlYmItODE1ZS00M2FjLWFmYzMtMDE4NDQwMGVkNzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNTMxNWIyNDhmNjcwZDhjYjI5MTU4MjhjMzJlM2NjYzcxNTEwYjBiZWQwMmMxN2IyYTI5M2M2MGI1ZDg1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y6sjQ5zQUKcsPR9u6lEQMBlEkx-BGSk_YEzNvcpJ0ik) ![mega.rcp](https://private-user-images.githubusercontent.com/24873576/331208112-86407630-de72-4cb5-ae4c-7beda944c986.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMTItODY0MDc2MzAtZGU3Mi00Y2I1LWFlNGMtN2JlZGE5NDRjOTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTdmYTBjMmY0ZWUwZjcxY2VkZGY5ZTliODAzMmI2YmY4YmEzMGFjYmY2MzQ4NGQxZmVmZjZiMGU5N2FjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nin8pfQxq2O0GxdsR3Rb29pjiQiPF9uXyis0nyN4_0Q) ![mnmchn88.rcp](https://private-user-images.githubusercontent.com/24873576/331208117-571c0e8d-3d71-4f0b-90c4-9b1a689e79db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzI1MjUsIm5iZiI6MTcxNTg3MjIyNSwicGF0aCI6Ii8yNDg3MzU3Ni8zMzEyMDgxMTctNTcxYzBlOGQtM2Q3MS00ZjBiLTkwYzQtOWIxYTY4OWU3OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1MTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZDJkNGUwZjRmZmViZmVjMzYyYmFmY2JlNDQwNmVjMzRkZDc5NjNmMmI3ODJkYmI3ODE1YmUyNTg2NGYwY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TphCOL7f4KAKP4Q9WO5tkpMFDoF2GfbPWiezBccG1kM)

Well, I don't know how to read or write Japanese so it's difficult for me to tell what's wrong. Wrong characters? Wrong encoding? Wrong language? It's a simple heuristic that first tries Shift-JIS and then EUC-JP. But if any ANSI characters are mixed in then it's easy to make a wrong conclusion. I'm experimenting with uchardet to see if I can use that.

**Comment by Mohamed00** [comment] 2024-05-16 15:25
You might also want to try reloading info using the option in the tools menu of properties, in case foobar is caching old tags.

**Comment by basic2004** [comment] 2024-05-16 15:39
> You might also want to try reloading info using the option in the tools menu of properties, in case foobar is caching old tags.

Thanks, I just reloaded info and checked detected correctly.

**Comment by internetakias** [comment] 2024-05-16 20:35
By the way, 32 channel midi files like NIGHT.g36 still play incorrectly

**Comment by internetakias** [comment] 2024-05-16 20:42
Here's a video demonstration, foo_midi midi conversion on the left, RCPCVC conversion on the right

https://github.com/stuerp/foo_midi/assets/5077063/939abcf6-087d-4c8c-b5b0-548b4cba27a7

**Comment by internetakias** [comment] 2024-05-16 20:53
Video demonstration here, foo_midi conversion on the left, RCPCVC on the right

https://github.com/stuerp/foo_midi/assets/5077063/930cd19a-3ff0-47e9-a660-9c04a0fb18b5

**Comment by stuerp** [comment] 2024-05-22 10:21
> Video demonstration here, foo_midi conversion on the left, RCPCVC on the right
> 
>  sekaiju.mp4

OK, I can see and hear the difference. At first sight it looks like rounding error in the timestamp calculation. Like they say in 'Amadeus': too many notes...

**Comment by stuerp** [comment] 2024-06-23 12:45
Released as v2.11.0.0. I'll search for a solution to the timing issue later.

**Closed by stuerp** 2024-06-23 12:45 UTC
Labels: enhancement
