### ISSUE TITLE
Loop markers don't work with VSTis

### ISSUE THREAD

**Issue by KiON-GiON** [stuerp/foo_midi#8] opened 2023-06-16 16:50 UTC
Any MIDI that has loop markers, like FF7PC, The RPG Maker ones, Touhou, XMI, etc. doesn't work with any VSTi when I configure them. The most notable usage of this would be the S-YXG50 VSTi.
If you play any FF7PC MIDI, the loop will not work and the sequence playback stops. This issue is present in the latest official foo_midi and this one too.

**Comment by stuerp** [comment] 2023-06-16 18:23
The loop markers are independent of the player so it is probably a general issue. Can you provide me with an example file?

**Comment by KiON-GiON** [comment] 2023-06-16 18:49
I can provide an example. [This MIDI](https://drive.google.com/uc?id=1b1mfTeFSxs6udggANYE6tRU0_CTRHGn-) from FF7PC. It should loop around 23 secs. loop begins at around 5 secs.

**Comment by stuerp** [comment] 2023-06-16 20:32
I was able to reproduce the problem with VSTi. Oddly enough BASSMIDI loops once with a fade while Emu de MIDI loops indefinitely. I'll have to dive into the loop code.

**Comment by stuerp** [comment] 2023-06-17 13:06
Fixed in the next release. The loop works now for all players.

I'll leave the issue open until you are able to confirm it.

**Comment by stuerp** [comment] 2023-06-21 18:06
I released a beta version with the fix. If you feel up to it, please try it and let me know if this fixes your issue.

**Comment by KiON-GiON** [comment] 2023-06-21 20:01
It works now! However, when the MIDI reaches the 2nd loop, I can't go forward and backward, otherwise the playback stops. I don't know if that's an issue though or it's the intended behavior.

**Comment by stuerp** [comment] 2023-06-25 17:54
It is the same behavior as the last version of the MIDI Player by Kode54. That said, I don't like it either. Also, the length reported in the status bar is double of what is displayed in the playlist. I'll probably release this version as is and keep looking for a permanent fix.

**Comment by stuerp** [comment] 2023-07-25 18:36
Since the original issue is fixed I'll close this issue.

I don't see a simple fix for the length issue because that's the way synthesized files with loops are generated in foobar2000. I can reposition the track position to a certain point in time, not to a particular event.

**Closed by stuerp** 2023-07-25 18:36 UTC
