### ISSUE TITLE
foo_midi crashes when adding a 0-byte .mid file

### ISSUE THREAD

**Issue by hlandau** [stuerp/foo_midi#4] opened 2023-05-12 18:03 UTC
Replicated under 32-bit wine with 32-bit foobar2000 v2, and 64-bit wine with 64-bit foobar2000 v2. This appears to be triggered by certain MIDI files contained in the "51,000 MIDI Files Saved from Geocities" collection, which is a 412 MiB ZIP file which was produced by Archive Team from their efforts to archive Geocities.com prior to its imminent shutdown. I usually feed this ZIP file directly to foobar2000 but doing so causes it to crash consistently. I bisected through all the MIDIs in this ZIP to figure out what file was causing it.

It turns out this is actually caused simply by an invalid 0-byte file with a `.mid` extension. Adding the file `09.mid`, containing zero bytes, reliably causes foobar2000 to crash when foo_midi is installed. No VSTs have been added nor have any foo_midi settings been changed, this is a completely default install.

It may also be useful to you to add the Geocities MIDI collection to your testing regime. If you want it, you probably won't have any difficulty finding a copy online, but if you do, just [email me](https://www.devever.net/~hl/contact) and I'll get you a copy.

Thanks for continuing to maintain this outstanding software. I use foobar2000 under foo_midi under wine because there is simply nothing better for playing MIDI files under the sun. The variety of MIDI engines offered and VSTi support is really something.

**Comment by stuerp** [comment] 2023-05-13 09:44
> It turns out this is actually caused simply by an invalid 0-byte file with a `.mid` extension. Adding the file `09.mid`, containing zero bytes, reliably causes foobar2000 to crash when foo_midi is installed.

Thanks for the detailed report. I stayed away from the MIDI parser because it is packaged separately from the player, assuming that most obvious bugs would already have been resolved by kode54.

I'll fix it in the next release.

**Comment by stuerp** [comment] 2023-05-14 13:38
I'm unable to reproduce it. Adding a single 0-byte file as standalone file, contained in a directory, added to the music library or resulting from an archive import (such as the Geocities archive) did not crash fb2k 2.0 x86 nor x64. Could it be a wine specific issue?

**Closed** 2023-05-17 17:57 UTC
